<a href="https://colab.research.google.com/github/subhamsam007/Numpy-and-pandas/blob/main/practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# New Section

In [ ]:
import numpy as np


In [ ]:
# @title
a=np.array([1,2,1,3])
a

array([1, 2, 1, 3])

In [ ]:
arr =np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr2=np.ones((4,8))
arr2

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
arr3 =np.linspace(1,6,10)
arr3

array([1.        , 1.55555556, 2.11111111, 2.66666667, 3.22222222,
       3.77777778, 4.33333333, 4.88888889, 5.44444444, 6.        ])

Random number  genarate function


In [ ]:
arr4=np.random.rand(10)
arr4

array([0.26738648, 0.57581652, 0.32408786, 0.88870748, 0.29171399,
       0.20990708, 0.72602821, 0.35970915, 0.13835504, 0.61025486])

In [ ]:
np.random.randn(10
)

array([ 1.93074956,  0.59786144,  2.92821006,  1.12532723, -0.63502812,
        0.13844155,  0.06862648,  0.02841059,  0.47805706, -0.50150668])

In [ ]:
np.random.randint(10,20,5)

array([17, 15, 12, 11, 14])

array attributes


In [ ]:
array=np.array([[1,2,3],[4,5,6],[7,8,9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
array.shape

(3, 3)

In [ ]:
array.size

9

array method


In [ ]:
np.sum(array,1)
np.max(array)

np.int64(9)

reshape and resize


In [ ]:
ap=np.arange(1,21)
ap

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
np.reshape(ap,(4,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

numpy indexing and slicing vector

In [ ]:
new_a= np.arange(1,11)
new_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
new_a[8::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

numpy indexing and licing of an maxrix

In [ ]:
new_b=np.arange(1,31).reshape(6,5)
print(new_b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [ ]:
slice=new_b[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [ ]:
import numpy as np


VAILD SUDOKU


In [ ]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [ ]:
sum_of_row=np.sum(s,axis= 1)
print(sum_of_row)
sum_of_row== 45

[45 45 45 45 45 45 45 45 45]


array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [ ]:
b=np.sum(s,axis=1)
print(b)
for i in b:
  if i!=45:
    print("no")
    break
else :print("sudoku")

[45 45 45 45 45 45 45 45 45]
sudoku


In [ ]:
c=np.sum(s,axis=0)
for j in c:
  if j!=45:
    print("no")
    break
else :print("sudoku")

sudoku


In [ ]:
s[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [ ]:
for i in range(0,9,3):
  for j in range(0,9,3):
    n=s[i:i+3,j:j+3]
    print(n.sum())

45
45
45
45
45
45
45
45
45


General Questions

In [ ]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [ ]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [ ]:
#Find the average age of students
np.mean(data[:,0])

np.float64(18.4)

In [ ]:
#Extract Math marks of all students.
print(data[:,1])


[85 92 76 65 90]


In [ ]:
#Find the highest Science mark.
print(np.max(data[:,2]))

95


In [ ]:
#Get details of the student who scored more than 90 in Math.
more90=data[data[:,1]>90]
print(more90)

[[19 92 88]]


In [ ]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [ ]:
#Increase Math marks of all students by 5.
i=data[:,1]+5
print(i)

[90 97 81 70 95]


In [ ]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [ ]:

#Find how many students are younger than 19.
young= data[data[:,0]<19]
print(len(young))


3
[[18 85 78]
 [17 76 95]
 [18 65 70]]


In [ ]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [ ]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:],1)

array([81.5, 90. , 85.5, 67.5, 87.5])